---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AppName:
    Type: String
Outputs:
  BucketURL:
    Value: !GetAtt
      - AppBucket
      - WebsiteURL
Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName:
        Ref: AppName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  AppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref AppBucket
                - /*
      Bucket: !Ref AppBucket
