---
head:
  title: "Hello World"
  author: "@juzbo"
  themes:
    bootstrap: "superhero"
    highlightjs: "ocean"
  google:
    analytics: "UA-150905941-1"
navbar:
  title: "Hello World"
about:
  params:
    icon_size: 32
  links:
    - href: "https://twitter.com/juzbo"
      src: "/assets/img/icons/twitter.png"
      title: "Twitter"
    - href: "https://gist.github.com/jhw"
      src: "/assets/img/icons/github.png"
      title: "Github"
    - href: "https://stackoverflow.com/users/124179/justin"
      src: "/assets/img/icons/stackoverflow.png"
      title: "StackOverflow"
    - href: "https://www.linkedin.com/in/justin-worrall-8076b26/"
      src: "/assets/img/icons/linkedin.png"
      title: "LinkedIn"
