---
head:
  title: "Hello World"
  author: "@juzbo"
  themes:
    bootstrap: "cerulean"
    highlightjs: "arduino-light"
  google:
    analytics: "UA-150905941-1"
navbar:
  title: "Hello World"
about:
  params:
    icon_size: 32
  links:
    - href: "https://twitter.com/juzbo"
      src: "/assets/img/icons/twitter.png"
      title: "Twitter"
